[package]
name = "Py03_Example"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
rayon = "1.5"

[lib]
crate-type = ["cdylib"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
