[package]
name = "py03_example"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
minifb = "0.27"
rayon = "1.5"
rand = "0.8"

[lib]
crate-type = ["cdylib"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
